/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2_andrescruz;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MBanegas
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        aa.cargarArchivo();
        for (int i = 0; i < aa.getListaAstronauta().size(); i++) {
            astronautas.add(aa.getListaAstronauta().get(i));
        }
        ap.cargarArchivo();
        for (int i = 0; i < ap.getListaPlanetas().size(); i++) {
            planetas.add(ap.getListaPlanetas().get(i));
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < planetas.size(); i++) {
            modelo.addElement(planetas.get(i));
        }
        cb_destinonave.setModel(modelo);
        cb_destinonave1.setModel(modelo);
        an.cargarArchivo();
        for (int i = 0; i < an.getListaNaves().size(); i++) {
            naves.add(an.getListaNaves().get(i));
        }
        tablaAstron();
        tablaNaves();
        tablaPlane();
    }

    public void tablaAstron() {
        tablaAstronauta.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nombre", "Nacionalidad", "Sueldo", "Experiencia", "Sexo", "Peso"
                }
        ));
        DefaultTableModel m1 = (DefaultTableModel) tablaAstronauta.getModel();
        tablaAstronauta.setModel(m1);
        for (int i = 0; i < astronautas.size(); i++) {
            Astronauta aqui = astronautas.get(i);
            Object[] Row = {aqui.getNombre(), aqui.getNacionalidad(), aqui.getSueldo(), aqui.getExperiencia(), aqui.getSexo(), aqui.getPeso()};
            m1.addRow(Row);
        }
        tablaAstronauta.setModel(m1);
    }

    public void tablaNaves() {
        try {
            tablaNave.setModel(new javax.swing.table.DefaultTableModel(
                    new Object[][]{},
                    new String[]{
                        "Numero de Serie", "Destino", "Velocidad", "Material", "Peso", "Despegue"
                    }
            ));

            DefaultTableModel m2 = (DefaultTableModel) tablaNave.getModel();
            for (int i = 0; i < naves.size(); i++) {
                Naves aqui = naves.get(i);
                Object[] Row = new Object[6];
                if (aqui instanceof Sonda) {
                    Row[0] = aqui.getNum_serie();
                    Row[1] = aqui.getDestino();
                    Row[2] = aqui.getVelocidad();
                    Row[3] = ((Sonda) aqui).getMaterial();
                    Row[4] = ((Sonda) aqui).getPeso();
                } else if (aqui instanceof Tripulada) {
                    Row[0] = aqui.getNum_serie();
                    Row[1] = aqui.getDestino();
                    Row[2] = aqui.getVelocidad();
                    Row[5] = ((Tripulada) aqui).getDespegue();
                }
                m2.addRow(Row);
            }
            tablaNave.setModel(m2);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void tablaPlane() {
        tablaPlaneta.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nombre", "Temperatura", "Tiene Anillos", "Superficie", "Distancia de la Tierra"
                }
        ));
        DefaultTableModel m3 = (DefaultTableModel) tablaPlaneta.getModel();
        for (int i = 0; i < planetas.size(); i++) {
            Planeta aqui = planetas.get(i);
            Object[] Row = {aqui.getNombre(), aqui.getTemp(), aqui.isAnillos(), aqui.getSuperficie(), aqui.getDistancia()};
            m3.addRow(Row);
        }
        tablaPlaneta.setModel(m3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crearAstro = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_nomastro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_nacastro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        js_sueldoastro = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        js_expastro = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        rb_m = new javax.swing.JRadioButton();
        rb_f = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        js_pesoastro = new javax.swing.JSpinner();
        bt_crearastro = new javax.swing.JButton();
        crearPlan = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tf_nomplan = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        js_tempplan = new javax.swing.JSpinner();
        cb_anillosplan = new javax.swing.JCheckBox();
        jLabel23 = new javax.swing.JLabel();
        tf_superplan = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        js_displan = new javax.swing.JSpinner();
        bt_crearplan = new javax.swing.JButton();
        crearNave = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        tf_numserienave = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        cb_destinonave = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        js_velnave = new javax.swing.JSpinner();
        jLabel33 = new javax.swing.JLabel();
        cb_tiponave = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        tf_materialsondanave = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        js_pesosondanave = new javax.swing.JSpinner();
        jLabel36 = new javax.swing.JLabel();
        tf_despeguenave = new javax.swing.JTextField();
        bt_crearnave = new javax.swing.JButton();
        modAstro = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_nomastrom = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tf_nacastrom = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        js_sueldoastrom = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        js_expastrom = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        rb_mm = new javax.swing.JRadioButton();
        rb_fm = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        js_pesoastrom = new javax.swing.JSpinner();
        bt_modastro = new javax.swing.JButton();
        modPlan = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        tf_nomplan1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        js_tempplan1 = new javax.swing.JSpinner();
        cb_anillosplan1 = new javax.swing.JCheckBox();
        jLabel27 = new javax.swing.JLabel();
        tf_superplan1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        js_displan1 = new javax.swing.JSpinner();
        bt_crearplan1 = new javax.swing.JButton();
        modNave = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        tf_numserienave1 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        cb_destinonave1 = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        js_velnave1 = new javax.swing.JSpinner();
        jLabel41 = new javax.swing.JLabel();
        cb_tiponave1 = new javax.swing.JComboBox<>();
        jLabel42 = new javax.swing.JLabel();
        tf_materialsondanave1 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        js_pesosondanave1 = new javax.swing.JSpinner();
        jLabel44 = new javax.swing.JLabel();
        tf_despeguenave1 = new javax.swing.JTextField();
        bt_crearnave1 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        popupplan = new javax.swing.JPopupMenu();
        jmi_modplan = new javax.swing.JMenuItem();
        jmi_elimplan = new javax.swing.JMenuItem();
        popupastro = new javax.swing.JPopupMenu();
        jmi_modastro = new javax.swing.JMenuItem();
        jmi_elimastro = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaNave = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPlaneta = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaAstronauta = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableExpedicion = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        bt_exp = new javax.swing.JButton();
        bt_astro = new javax.swing.JButton();
        bt_plan = new javax.swing.JButton();
        bt_nave = new javax.swing.JButton();

        jLabel5.setText("Nombre:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Crear Astronauta");

        jLabel7.setText("Nacionalidad:");

        jLabel8.setText("Sueldo:");

        js_sueldoastro.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        jLabel9.setText("Experiencia:");

        js_expastro.setModel(new javax.swing.SpinnerNumberModel(1, 0, 100, 1));

        jLabel10.setText("Sexo:");

        buttonGroup1.add(rb_m);
        rb_m.setText("M");

        buttonGroup1.add(rb_f);
        rb_f.setText("F");

        jLabel11.setText("Peso:");

        js_pesoastro.setModel(new javax.swing.SpinnerNumberModel(50.0d, 20.0d, 500.0d, 1.0d));

        bt_crearastro.setText("Crear");
        bt_crearastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearastroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_nomastro)
                    .addComponent(tf_nacastro)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(js_sueldoastro)
                                .addComponent(js_expastro, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(rb_m)
                                    .addGap(18, 18, 18)
                                    .addComponent(rb_f))
                                .addComponent(js_pesoastro))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(bt_crearastro)))
                        .addGap(0, 104, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_nomastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(tf_nacastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(js_sueldoastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(js_expastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(rb_m)
                    .addComponent(rb_f))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(js_pesoastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bt_crearastro)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout crearAstroLayout = new javax.swing.GroupLayout(crearAstro.getContentPane());
        crearAstro.getContentPane().setLayout(crearAstroLayout);
        crearAstroLayout.setHorizontalGroup(
            crearAstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        crearAstroLayout.setVerticalGroup(
            crearAstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel19.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Crear Planeta");

        jLabel20.setText("Nombre");

        jLabel21.setText("Temperatura");

        js_tempplan.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 300.0d, 1.0d));

        cb_anillosplan.setText("Tiene Anillos");
        cb_anillosplan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_anillosplanActionPerformed(evt);
            }
        });

        jLabel23.setText("Superficie");

        jLabel24.setText("Distancia");

        js_displan.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        bt_crearplan.setText("Crear");
        bt_crearplan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearplanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(tf_nomplan))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_anillosplan)
                                    .addComponent(js_tempplan, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(44, 44, 44)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bt_crearplan)
                                    .addComponent(js_displan, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 75, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_superplan)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tf_nomplan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(js_tempplan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_anillosplan)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(tf_superplan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(js_displan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(bt_crearplan)
                .addGap(0, 36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout crearPlanLayout = new javax.swing.GroupLayout(crearPlan.getContentPane());
        crearPlan.getContentPane().setLayout(crearPlanLayout);
        crearPlanLayout.setHorizontalGroup(
            crearPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        crearPlanLayout.setVerticalGroup(
            crearPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel29.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Crear Nave");

        jLabel30.setText("Numero de Serie");

        jLabel31.setText("Destino");

        jLabel32.setText("Velocidad");

        js_velnave.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, null, 1.0d));

        jLabel33.setText("Tipo de Nave");

        cb_tiponave.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sonda", "Tripulada" }));

        jLabel34.setText("Material (Sonda)");

        tf_materialsondanave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_materialsondanaveActionPerformed(evt);
            }
        });

        jLabel35.setText("Peso (Sonda)");

        js_pesosondanave.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, null, 1.0d));

        jLabel36.setText("Lugar de Despegue (Tripulada)");

        bt_crearnave.setText("Crear");
        bt_crearnave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearnaveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_numserienave))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_materialsondanave))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addGap(25, 25, 25)
                        .addComponent(js_pesosondanave))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel31)
                                    .addGap(18, 18, 18)
                                    .addComponent(cb_destinonave, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel32)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(js_velnave)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addGap(18, 18, 18)
                                .addComponent(cb_tiponave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel36))
                        .addGap(0, 70, Short.MAX_VALUE))
                    .addComponent(tf_despeguenave, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(bt_crearnave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(tf_numserienave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(cb_destinonave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(js_velnave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(cb_tiponave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(tf_materialsondanave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(js_pesosondanave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_despeguenave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_crearnave)
                .addGap(0, 40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout crearNaveLayout = new javax.swing.GroupLayout(crearNave.getContentPane());
        crearNave.getContentPane().setLayout(crearNaveLayout);
        crearNaveLayout.setHorizontalGroup(
            crearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        crearNaveLayout.setVerticalGroup(
            crearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel12.setText("Nombre:");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Modificar Astronauta");

        jLabel14.setText("Nacionalidad:");

        jLabel15.setText("Sueldo:");

        js_sueldoastrom.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        jLabel16.setText("Experiencia:");

        js_expastrom.setModel(new javax.swing.SpinnerNumberModel(1, 0, 100, 1));

        jLabel17.setText("Sexo:");

        buttonGroup1.add(rb_mm);
        rb_mm.setSelected(true);
        rb_mm.setText("M");

        buttonGroup1.add(rb_fm);
        rb_fm.setText("F");

        jLabel18.setText("Peso:");

        js_pesoastrom.setModel(new javax.swing.SpinnerNumberModel(50, 20, 500, 1));

        bt_modastro.setText("Modificar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_nomastrom)
                    .addComponent(tf_nacastrom)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(js_sueldoastrom)
                                .addComponent(js_expastrom, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(rb_mm)
                                    .addGap(18, 18, 18)
                                    .addComponent(rb_fm))
                                .addComponent(js_pesoastrom))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(bt_modastro)))
                        .addGap(0, 59, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_nomastrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(tf_nacastrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(js_sueldoastrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(js_expastrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(rb_mm)
                    .addComponent(rb_fm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(js_pesoastrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bt_modastro)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout modAstroLayout = new javax.swing.GroupLayout(modAstro.getContentPane());
        modAstro.getContentPane().setLayout(modAstroLayout);
        modAstroLayout.setHorizontalGroup(
            modAstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        modAstroLayout.setVerticalGroup(
            modAstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel22.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Modificar Planeta");

        jLabel25.setText("Nombre");

        jLabel26.setText("Temperatura");

        js_tempplan1.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 300.0d, 1.0d));

        cb_anillosplan1.setText("Tiene Anillos");
        cb_anillosplan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_anillosplan1ActionPerformed(evt);
            }
        });

        jLabel27.setText("Superficie");

        jLabel28.setText("Distancia");

        js_displan1.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        bt_crearplan1.setText("Crear");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(tf_nomplan1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_anillosplan1)
                                    .addComponent(js_tempplan1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(44, 44, 44)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bt_crearplan1)
                                    .addComponent(js_displan1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 49, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_superplan1)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(tf_nomplan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(js_tempplan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_anillosplan1)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(tf_superplan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(js_displan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(bt_crearplan1)
                .addGap(0, 40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout modPlanLayout = new javax.swing.GroupLayout(modPlan.getContentPane());
        modPlan.getContentPane().setLayout(modPlanLayout);
        modPlanLayout.setHorizontalGroup(
            modPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        modPlanLayout.setVerticalGroup(
            modPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel37.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Modificar Nave");

        jLabel38.setText("Numero de Serie");

        jLabel39.setText("Destino");

        jLabel40.setText("Velocidad");

        js_velnave1.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, null, 1.0d));

        jLabel41.setText("Tipo de Nave");

        cb_tiponave1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sonda", "Tripulada" }));

        jLabel42.setText("Material (Sonda)");

        tf_materialsondanave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_materialsondanave1ActionPerformed(evt);
            }
        });

        jLabel43.setText("Peso (Sonda)");

        js_pesosondanave1.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, null, 1.0d));

        jLabel44.setText("Lugar de Despegue (Tripulada)");

        bt_crearnave1.setText("Modificar");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_numserienave1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_materialsondanave1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel43)
                        .addGap(25, 25, 25)
                        .addComponent(js_pesosondanave1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel39)
                                    .addGap(18, 18, 18)
                                    .addComponent(cb_destinonave1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel40)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(js_velnave1)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel41)
                                .addGap(18, 18, 18)
                                .addComponent(cb_tiponave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel44))
                        .addGap(0, 72, Short.MAX_VALUE))
                    .addComponent(tf_despeguenave1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(bt_crearnave1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(tf_numserienave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(cb_destinonave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(js_velnave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(cb_tiponave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(tf_materialsondanave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(js_pesosondanave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel44)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_despeguenave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_crearnave1)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout modNaveLayout = new javax.swing.GroupLayout(modNave.getContentPane());
        modNave.getContentPane().setLayout(modNaveLayout);
        modNaveLayout.setHorizontalGroup(
            modNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        modNaveLayout.setVerticalGroup(
            modNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jmi_modplan.setText("Modificar");
        popupplan.add(jmi_modplan);

        jmi_elimplan.setText("Eliminar");
        jmi_elimplan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_elimplanActionPerformed(evt);
            }
        });
        popupplan.add(jmi_elimplan);

        jmi_modastro.setText("Modificar");
        popupastro.add(jmi_modastro);

        jmi_elimastro.setText("Eliminar");
        popupastro.add(jmi_elimastro);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaNave.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero de Serie", "Destino", "Velocidad", "Material", "Peso", "Despegue"
            }
        ));
        tablaNave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaNaveMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaNave);

        tablaPlaneta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Temperatura", "Tiene Anillos", "Superficie", "Distancia de la Tierra"
            }
        ));
        tablaPlaneta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPlanetaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaPlaneta);

        tablaAstronauta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Nacionalidad", "Sueldo", "Experiencia", "Sexo", "Peso"
            }
        ));
        tablaAstronauta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAstronautaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaAstronauta);

        jLabel1.setText("Astronautas");

        jLabel2.setText("Planetas");

        jLabel3.setText("Naves");

        tableExpedicion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Planeta Viaje", "Viaje Completo"
            }
        ));
        jScrollPane4.setViewportView(tableExpedicion);

        jLabel4.setText("Expediciones");

        bt_exp.setText("Expedicion");

        bt_astro.setText("Crear Astronautas");
        bt_astro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_astroMouseClicked(evt);
            }
        });

        bt_plan.setText("Crear Planetas");
        bt_plan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_planMouseClicked(evt);
            }
        });

        bt_nave.setText("Crear Naves");
        bt_nave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_naveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane4))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_exp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_astro, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(bt_plan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_nave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_exp)
                        .addGap(30, 30, 30)
                        .addComponent(bt_astro)
                        .addGap(14, 14, 14)
                        .addComponent(bt_plan)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bt_nave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_anillosplanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_anillosplanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_anillosplanActionPerformed

    private void cb_anillosplan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_anillosplan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_anillosplan1ActionPerformed

    private void tf_materialsondanaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_materialsondanaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_materialsondanaveActionPerformed

    private void tf_materialsondanave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_materialsondanave1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_materialsondanave1ActionPerformed

    private void tablaAstronautaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAstronautaMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            popupastro.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tablaAstronautaMouseClicked

    private void tablaPlanetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPlanetaMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            popupplan.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tablaPlanetaMouseClicked

    private void tablaNaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaNaveMouseClicked
        // TODO add your handling code here:        
    }//GEN-LAST:event_tablaNaveMouseClicked

    private void bt_astroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_astroMouseClicked
        // TODO add your handling code here:
        crearAstro.setModal(true);
        crearAstro.setLocationRelativeTo(this);
        crearAstro.pack();
        crearAstro.setVisible(true);
    }//GEN-LAST:event_bt_astroMouseClicked

    private void bt_planMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_planMouseClicked
        // TODO add your handling code here:
        crearPlan.setModal(true);
        crearPlan.setLocationRelativeTo(this);
        crearPlan.pack();
        crearPlan.setVisible(true);
    }//GEN-LAST:event_bt_planMouseClicked

    private void bt_naveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_naveMouseClicked
        // TODO add your handling code here:
        crearNave.setModal(true);
        crearNave.setLocationRelativeTo(this);
        crearNave.pack();
        crearNave.setVisible(true);
    }//GEN-LAST:event_bt_naveMouseClicked

    private void bt_crearastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearastroMouseClicked
        // TODO add your handling code here:
        try {
            String nombre = tf_nomastro.getText();
            String nac = tf_nacastro.getText();
            double sueldo = (double) js_sueldoastro.getValue();
            int exp = (int) js_expastro.getValue();
            String sexo;
            if (rb_m.isSelected()) {
                sexo = "Masculino";
            } else {
                sexo = "Femenino";
            }
            double peso = (double) js_pesoastro.getValue();
            astronautas.add(new Astronauta(nombre, nac, sueldo, exp, sexo, peso));
            aa.setListaAstronauta(astronautas);
            aa.escribirArchivo();
            aa.cargarArchivo();
            tf_nacastro.setText("");
            tf_nomastro.setText("");
            js_sueldoastro.setValue(0);
            js_expastro.setValue(1);
            rb_f.setSelected(false);
            rb_m.setSelected(true);
            js_pesoastro.setValue(50);
            tablaAstron();
            crearAstro.dispose();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_bt_crearastroMouseClicked

    private void bt_crearplanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearplanMouseClicked
        // TODO add your handling code here:
        try {
            String nombre = tf_nomplan.getText();
            double temp = (double) js_tempplan.getValue();
            boolean anillos = cb_anillosplan.isSelected();
            String superficie = tf_superplan.getText();
            double distancia = (double) js_displan.getValue();
            planetas.add(new Planeta(nombre, temp, anillos, superficie, distancia));
            ap.setListaPlanetas(planetas);
            ap.escribirArchivo();
            ap.cargarArchivo();
            tablaPlane();
            tf_nomplan.setText("");
            js_tempplan.setValue(0);
            cb_anillosplan.setSelected(false);
            tf_superplan.setText("");
            js_displan.setValue(0);
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            for (int i = 0; i < planetas.size(); i++) {
                modelo.addElement(planetas.get(i));
            }
            cb_destinonave.setModel(modelo);
            cb_destinonave1.setModel(modelo);
            crearPlan.dispose();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_bt_crearplanMouseClicked

    private void bt_crearnaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearnaveMouseClicked
        // TODO add your handling code here:
        try {
            String num_ser = tf_numserienave.getText();
            Planeta destino = (Planeta) cb_destinonave.getSelectedItem();
            double vel = (double) js_velnave.getValue();
            String tipo = cb_tiponave.getSelectedItem().toString();
            if (tipo.equals("Sonda")) {
                String material = tf_materialsondanave.getText();
                double peso = (double) js_pesosondanave.getValue();
                naves.add(new Sonda(material, peso, num_ser, destino, vel));
            } else {
                String despegue = tf_despeguenave.getText();
                naves.add(new Tripulada(despegue, num_ser, destino, vel));
            }
            an.setListaNaves(naves);
            an.escribirArchivo();
            an.cargarArchivo();
            tablaNaves();
            tf_numserienave.setText("");
            cb_destinonave.setSelectedIndex(0);
            js_velnave.setValue(1);
            cb_tiponave.setSelectedIndex(0);
            tf_materialsondanave.setText("");
            js_pesosondanave.setValue(1);
            tf_despeguenave.setText("");
            crearNave.dispose();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bt_crearnaveMouseClicked

    private void jmi_elimplanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_elimplanActionPerformed
        // TODO add your handling code here:
        if (tablaPlaneta.getSelectedRow() >= 0) {
            planetas.remove(tablaPlaneta.getSelectedRow());
            ap.setListaPlanetas(planetas);
            ap.escribirArchivo();
            ap.cargarArchivo();
            tablaPlane();
        }
    }//GEN-LAST:event_jmi_elimplanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_astro;
    private javax.swing.JButton bt_crearastro;
    private javax.swing.JButton bt_crearnave;
    private javax.swing.JButton bt_crearnave1;
    private javax.swing.JButton bt_crearplan;
    private javax.swing.JButton bt_crearplan1;
    private javax.swing.JButton bt_exp;
    private javax.swing.JButton bt_modastro;
    private javax.swing.JButton bt_nave;
    private javax.swing.JButton bt_plan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cb_anillosplan;
    private javax.swing.JCheckBox cb_anillosplan1;
    private javax.swing.JComboBox<String> cb_destinonave;
    private javax.swing.JComboBox<String> cb_destinonave1;
    private javax.swing.JComboBox<String> cb_tiponave;
    private javax.swing.JComboBox<String> cb_tiponave1;
    private javax.swing.JDialog crearAstro;
    private javax.swing.JDialog crearNave;
    private javax.swing.JDialog crearPlan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JMenuItem jmi_elimastro;
    private javax.swing.JMenuItem jmi_elimplan;
    private javax.swing.JMenuItem jmi_modastro;
    private javax.swing.JMenuItem jmi_modplan;
    private javax.swing.JSpinner js_displan;
    private javax.swing.JSpinner js_displan1;
    private javax.swing.JSpinner js_expastro;
    private javax.swing.JSpinner js_expastrom;
    private javax.swing.JSpinner js_pesoastro;
    private javax.swing.JSpinner js_pesoastrom;
    private javax.swing.JSpinner js_pesosondanave;
    private javax.swing.JSpinner js_pesosondanave1;
    private javax.swing.JSpinner js_sueldoastro;
    private javax.swing.JSpinner js_sueldoastrom;
    private javax.swing.JSpinner js_tempplan;
    private javax.swing.JSpinner js_tempplan1;
    private javax.swing.JSpinner js_velnave;
    private javax.swing.JSpinner js_velnave1;
    private javax.swing.JDialog modAstro;
    private javax.swing.JDialog modNave;
    private javax.swing.JDialog modPlan;
    private javax.swing.JPopupMenu popupastro;
    private javax.swing.JPopupMenu popupplan;
    private javax.swing.JRadioButton rb_f;
    private javax.swing.JRadioButton rb_fm;
    private javax.swing.JRadioButton rb_m;
    private javax.swing.JRadioButton rb_mm;
    private javax.swing.JTable tablaAstronauta;
    private javax.swing.JTable tablaNave;
    private javax.swing.JTable tablaPlaneta;
    private javax.swing.JTable tableExpedicion;
    private javax.swing.JTextField tf_despeguenave;
    private javax.swing.JTextField tf_despeguenave1;
    private javax.swing.JTextField tf_materialsondanave;
    private javax.swing.JTextField tf_materialsondanave1;
    private javax.swing.JTextField tf_nacastro;
    private javax.swing.JTextField tf_nacastrom;
    private javax.swing.JTextField tf_nomastro;
    private javax.swing.JTextField tf_nomastrom;
    private javax.swing.JTextField tf_nomplan;
    private javax.swing.JTextField tf_nomplan1;
    private javax.swing.JTextField tf_numserienave;
    private javax.swing.JTextField tf_numserienave1;
    private javax.swing.JTextField tf_superplan;
    private javax.swing.JTextField tf_superplan1;
    // End of variables declaration//GEN-END:variables
    ArrayList<Planeta> planetas = new ArrayList();
    ArrayList<Astronauta> astronautas = new ArrayList();
    ArrayList<Naves> naves = new ArrayList();
    ArrayList<Astronauta> nodisponibles = new ArrayList();
    boolean haynaves = false, hayastronautas = false, hayplanetas = false;
    adminAstronauta aa = new adminAstronauta("./Astronautas.aecb");
    adminNaves an = new adminNaves("./Naves.aecb");
    adminPlanetas ap = new adminPlanetas("./Planetas.aecb");
}
